import '@/styles/globals.css'
import SideBar from '../components/SideBar'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '../components/Login'
import { SessionProvider } from '../components/SessionProvider'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session=await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session} >
        
          {!session ? (
            <Login/>
          ): (

          
          <div className='flex '>
            <div className=''>
              <SideBar/>
            </div>
            <div className='bg-[#343541] flex-1 flex-col justify-between items-center'>
              {children}
              </div>
          </div>
          )}
        </SessionProvider>
        </body>
    </html>
  )
}
